### ISSUE TITLE
Question about keys with dots

### ISSUE THREAD

**Issue by loretoparisi** [alemures/fast-json#3]
Hi,
when waiting for a json key event's to fire, I cannot write a syntax for jsons were (unfortuantely) the key has a `.` within like

```json
{
  "mykey": {
    "myinnerkey.dotted": []
  }
}
```
```javascript
fastJson.on('mykey["myinnerkey.dotted"]', (value) => {
    console.log('mykey.myinnerkey.dotted' ->', value.toString());
});
```

Looking at the code, I assume this happens here:

```javascript
 _processPath(path) {
    if (!path) {
      return '/';
    }

    path = path.replace(/[\.\[]/g, '/');
    path = path.replace(/\]/g, '');
    return path[0] !== '/' ? '/' + path : path;
  }
```

but I don't figure out how to avoid `path = path.replace(/[\.\[]/g, '/');` for those inner `.`.

Thank you!

**Comment by alemures** [comment]
Hi, `master` version doesn't support that currently, it's fixed in `develop` providing a path as an array instead of as an string
```
fastJson.on(['mykey','myinnerkey.dotted'], (value) => {
  console.log(value)
});
```
I'm currently working in releasing a new version of fast-json and will be available soon. Also, I plan to make the key separator configurable so, path could be provided with `/` as a separator allowing `.` characters in the path ie: `mykey/myinnerkey.dotted`.
